'''
 # @ Author: Ahmad Shayaan
 # @ Create Time: 2021-12-17 12:07:51
 # @ Modified by: Mitas Ray
 # @ Modified time: 2022-01-14 23:07:00
 # @ Description:
 '''

NUM_OF_DAYS_IN_YEAR = 360

COUPON_FREQUENCY_DICT = {0:"Unknown",
                        1:"Semiannually",
                        2:"Monthly",
                        3:"Annually",
                        4:"Weekly",
                        5:"Quarterly",
                        6:"Every 2 years",
                        7:"Every 3 years",
                        8:"Every 4 years",
                        9:"Every 5 years",
                        10:"Every 7 years",
                        11:"Every 8 years",
                        12:"Biweekly",
                        13:"Changeable",
                        14:"Daily",
                        15:"Term mode",
                        16:"Interest at maturity",
                        17:"Bimonthly",
                        18:"Every 13 weeks",
                        19:"Irregular",
                        20:"Every 28 days",
                        21:"Every 35 days",
                        22:"Every 26 weeks",
                        23:"Not Applicable",
                        24:"Tied to prime",
                        25:"One time",
                        26:"Every 10 years",
                        27:"Frequency to be determined",
                        28:"Mandatory put",
                        29:"Every 52 weeks",
                        30:"When interest adjusts-commercial paper",
                        31:"Zero coupon",
                        32:"Certain years only",
                        33:"Under certain circumstances",
                        34:"Every 15 years",
                        35:"Custom",
                        36:"Single Interest Payment"}

LARGE_NUMBER = 1e6
VERY_LARGE_NUMBER = 1e9

COUPON_FREQUENCY_TYPE = {"Unknown":LARGE_NUMBER,
                         "Semiannually":2,
                         "Monthly":12,
                         "Annually":1,
                         "Weekly":52,
                         "Quarterly":4,
                         "Every 2 years":0.5,
                         "Every 3 years":1/3,
                         "Every 4 years":0.25,
                         "Every 5 years":0.2,
                         "Every 7 years":1/7,
                         "Every 8 years":1/8,
                         "Every 10 years":1/10,
                         "Biweekly": 26,
                         "Changeable":44,
                         "Daily":360,
                         "Interest at maturity":0,
                         "Not Applicable":LARGE_NUMBER}

IDENTIFIERS = ['rtrs_control_number', 'cusip']


BINARY = ['callable',
          'sinking',
          'zerocoupon',
          'is_non_transaction_based_compensation',
          'is_general_obligation',
          'callable_at_cav',           
          'extraordinary_make_whole_call', 
          'make_whole_call',
          'has_unexpired_lines_of_credit',
          'escrow_exists',
          ]

CATEGORICAL_FEATURES = ['rating',
                        'incorporated_state_code',
                        'trade_type',
                        'transaction_type',
                        'maturity_description_code',
                        'purpose_class']

NON_CAT_FEATURES = ['quantity',
                    'days_to_maturity',
                    'days_to_call',
                    'coupon',
                    'issue_amount',
                    'last_seconds_ago',
                    'last_yield_spread',
                    'days_to_settle',
                    'days_to_par',
                    'maturity_amount',
                    'issue_price', 
                    'orig_principal_amount',
                    'max_amount_outstanding',
                    'accrued_days',
                    'days_in_interest_payment']

TRADE_HISTORY = ['trade_history']
TARGET = ['yield_spread']

PREDICTORS = BINARY + CATEGORICAL_FEATURES + NON_CAT_FEATURES + TARGET + TRADE_HISTORY

PURPOSE_CLASS_DICT = {1.0: 'Authority', 
                      2.0: 'Bond Anticipation Note', 
                      3.0: 'Building', 
                      4.0: 'Capital Loan Notes', 
                      5.0: 'Certificates Of Participation', 
                      6.0: 'Corporate Purpose', 
                      7.0: 'Drainage District', 
                      8.0: 'Economic Development Revenue', 
                      9.0: 'Education', 
                      10.0: 'Environment', 
                      11.0: 'Equipment', 
                      12.0: 'Federal Aid Note', 
                      13.0: 'Fire District', 
                      14.0: 'Flood Water Sewer Disposal', 
                      15.0: 'General Purpose', 
                      16.0: 'Grant Anticipation Note', 
                      17.0: 'Health', 
                      18.0: 'Housing', 
                      19.0: 'Improvement', 
                      20.0: 'Industrial Development Revenue', 
                      21.0: 'Library District', 
                      22.0: 'Metropolitan District', 
                      23.0: 'Miscellaneous', 
                      24.0: 'Municipal Bond Bank', 
                      25.0: 'Municipal Utilities District', 
                      26.0: 'Park District', 
                      27.0: 'Parking Authority', 
                      28.0: 'Pollution Control Revenue', 
                      29.0: 'Pool Financing Authority', 
                      30.0: 'Promissory Note', 
                      31.0: 'Public Housing Authority', 
                      32.0: 'Public Utility District', 
                      33.0: 'Racetrack/Casino', 
                      34.0: 'Recreation Authority', 
                      35.0: 'Revenue Anticipation Note', 
                      36.0: 'Sanitation District', 
                      37.0: 'School District', 
                      38.0: 'Special Assessment', 
                      39.0: 'Special Obligation', 
                      40.0: 'State and Federal Anticipation Note', 
                      41.0: 'State and Grant Anticipation Note', 
                      42.0: 'State Anticipation Notes', 
                      43.0: 'State Store', 
                      44.0: 'Tax and Revenue Anticipation', 
                      45.0: 'Tax Anticipation Note', 
                      46.0: 'Tax Revenue', 
                      47.0: 'Temporary Notes', 
                      48.0: 'Transportation', 
                      49.0: 'Tribal Bonds', 
                      50.0: 'Utility', 
                      51.0: 'Various Purpose', 
                      52.0: 'Veterans', 
                      53.0: 'Warrants'}

MUNI_ISSUE_TYPE_DICT = {1.0: 'Build America Bonds Direct Pay', 
                        2.0: 'Build America Bonds Tax Credit', 
                        3.0: 'New Clean Renewable Energy Bonds Tax Credit', 
                        4.0: 'New Clean Renewable Energy Bonds Direct Pay', 
                        5.0: 'Qualified Energy Conservation Bonds Tax Credit', 
                        6.0: 'Qualified Energy Conservation Bonds Direct Pay', 
                        7.0: 'Qualified School Construction Bonds Tax Credit', 
                        8.0: 'Qualified  School Construction Bonds Direct Pay', 
                        9.0: 'Qualified Zone Academy Bonds Tax Credit', 
                        10.0: 'Qualified Zone Academy Bonds Direct Pay', 
                        11.0: 'Recovery Zone Econ Dev Build America Bonds Direct Pay', 
                        12.0: 'Recovery Zone Facilities Bonds', 
                        13.0: 'Tribal Economic Development Bonds', 
                        14.0: 'Green Bonds', 
                        15.0: 'Municipal Liquidity Facility', 
                        16.0: 'Property Assessed Clean Energy'}

SALE_TYPE_DICT = {0: 'Unknown', 
                  1: 'Competitive', 
                  2: 'Negotiated', 
                  3: 'Limited', 
                  4: 'Private placement', 
                  5: 'Remarketing'}

ORIG_INSTRUMENT_ENHANCEMENT_TYPE_DICT = {1.0: 'Custodial receipt', 
                                         2.0: 'Periodic auction/inverse floater', 
                                         3.0: 'Prem municipal bond receipt', 
                                         4.0: 'Pre-refunded', 
                                         5.0: 'Third party put/tender option bond', 
                                         6.0: 'Remarketing', 
                                         7.0: 'Secondarily insured', 
                                         8.0: 'Unit put & secondarily insured', 
                                         9.0: 'Third party put unit', 
                                         10.0: 'Unrefunded balance'}

OTHER_ENHANCEMENT_TYPE_DICT = {0.0: 'Unknown',
                               1.0: 'GIC with',
                               2.0: 'State guaranteed',
                               3.0: 'State qualified school aid (MI, NJ, PA Only)',
                               4.0: 'Certificate of Deposit-FDIC',
                               5.0: 'Certificate of Deposit-FSLIC',
                               6.0: 'Guaranteed by',
                               7.0: 'City or County Gtd',
                               8.0: 'Guaranteed by the U.S. government',
                               9.0: 'Loan purchase agreement',
                               10.0: 'Certificate of Deposit-FDIC & FSLIC',
                               11.0: 'Bankers Acceptance',
                               12.0: 'Collateralized purchase agreement',
                               13.0: 'Qualified municipal bonds',
                               14.0: 'Gtd: Nat Rural Utilities Co-op Fin Corp',
                               15.0: 'State pool inv fd gtd',
                               16.0: 'Reinsurance',
                               17.0: 'Parent CUSIP insured',
                               18.0: 'State school aid program',
                               19.0: 'Loans to lenders agreement',
                               20.0: 'Minn School Dist enh program',
                               21.0: 'Permanent school fund guaranteed (TX Only)',
                               22.0: 'Parent CUSIP Gtd',
                               23.0: 'Parent CUSIP enh by LOC',
                               24.0: 'Parent CUSIP partially refunded',
                               25.0: 'Print paid by U.S. govs in escrow',
                               26.0: 'GTD Student loans',
                               27.0: 'Print paid by oblig of Inter. Bk for Reconst & Dev',
                               28.0: 'Utah State School Ins',
                               29.0: 'Prepaid gas contract',
                               30.0: 'Prepaid electric contract',
                               31.0: 'Tobacco settlement',
                               32.0: 'Miss Adequate Educ program (MAEP)',
                               33.0: 'Collateralized',
                               34.0: 'ARKANSAS SCHOOL DISTRICT ENHANCEMENT PROGRAM',
                               35.0: 'CALIFORNIA INFRASTRUCTURE BK SCH AID INTERCEPT PG',
                               36.0: 'COLORADO SCHOOL DISTRICT ENHANCEMENT PROGRAM',
                               37.0: 'COLORADO HIGHER EDUCATION ENHANCEMENT PROGRAM',
                               38.0: 'GEORGIA SCHOOL DISTRICT INTERCEPT PROGRAM',
                               39.0: 'IDAHO SCHOOL BOND GUARANTY PROGRAM',
                               40.0: 'INDIANA SCHOOL DISTRICT ENHANCEMENT PROGRAM',
                               41.0: 'KENTUCKY PUBLIC UNIVERSITY INTERCEPT PROGRAM',
                               42.0: 'KENTUCKY SCHOOL DISTRICT ENHANCEMENT PROGRAM',
                               43.0: 'MASSACHUSETTS QUALIFIED BOND PROGRAM',
                               44.0: 'MARYLAND INFRASTRUCTURE FINANCING INTERCEPT PROG',
                               45.0: 'MICHIGAN SCHOOL BOND QUAL & LOAN PROG',
                               46.0: 'MINNESOTA CREDIT ENHANCEMENT PROGRAM',
                               47.0: 'MISSOURI DIRECT DEPOSIT AGREEMENT INTERCEPT PROG',
                               48.0: 'NORTH DAKOTA DEPT OF PUB INSTR SCH DIST CRED ENH',
                               49.0: 'NEW JERSEY SCHOOL BOND RESERVE ACT',
                               50.0: 'NEW JERSEY MUNICIPAL QUALIFIED BOND PROGRAM',
                               51.0: 'NEW MEXICO SCHOOL DISTRICT ENHANCEMENT PROGRAM',
                               52.0: 'NEVADA SCHOOL DISTRICT BOND GUARANTEE PROGRAM',
                               53.0: 'DASNY OMRDD INTERCEPT PROGRAM',
                               54.0: 'DASNY MASTER BOCES PROGRAM',
                               55.0: 'DASNY COURT FACILITIES PROGRAM',
                               56.0: 'DASNY MUNICIPAL HEALTH FACILITIES PROGRAM',
                               57.0: 'DASNY SCHOOL DISTRICT REVENUE BOND FINANCING PROG',
                               58.0: 'NEW YORK STATE SECTION 99 B INTERCEPT PROGRAM',
                               59.0: 'OHIO SCHOOL DISTRICT CREDIT ENHANCEMENT PROGRAM',
                               60.0: 'OHIO TECHNICAL AND COMMUNITY COLLEGE PROGRAM',
                               61.0: 'OREGON PENSION OBLIGATION STATE INTERCEPT PROGRAM',
                               62.0: 'PENNSYLVANIA ST PUB SCH BLDG AUTH LEASE INTERCEPT',
                               63.0: 'PENNSYLVANIA SCH DIST FISCAL AGENT AGRMT INTERCEPT',
                               64.0: 'PENNSYLVANIA ACT 150 SCH DIST INTERCEPT PROG',
                               65.0: 'RHODE ISLAND HLTH AND EDUC BLDG CORP INTERCEPT',
                               66.0: 'RHODE ISLAND HEBC 6 MONTH INTERCEPT PROGRAM',
                               67.0: 'SOUTH CAROLINA SCH DIST CREDIT ENHANCEMENT PROG',
                               68.0: 'TENNESSEE ST SCH BOARD AUTH HIGHER ED INTERCEPT',
                               69.0: 'TENNESSEE STATE SCH BOND AUTHORITY INTERCEPT PROG',
                               70.0: 'TEXAS HIGHER EDUCATION BOND PROGRAM',
                               71.0: 'VIRGINIA LOCALITIES INTERCEPT PROGRAM',
                               72.0: 'WEST VIRGINIA MUNICIPAL BOND COMMISSION PROGRAM',
                               73.0: 'WYOMING SCHOOL DISTRICT BOND GUARANTEE PROGRAM',
                               74.0: 'MICHIGAN STATE SCHOOL BOND LOAN FUND PROGRAM',
                               75.0: 'OREGON SCHOOL BOND GUARANTEE PROGRAM',
                               76.0: 'WASHINGTON SCHOOL BOND GUARANTY PROGRAM',
                               77.0: 'NEW JERSEY COUNTY COLLEGE ENHANCEMENT BOND PROGRAM',
                               78.0: 'ARKANSAS SCHOOL DISTRICT ENH PROGRAM (PRE-DEFAULT)',
                               79.0: 'IDAHO SALES TAX GUARANTY PROGRAM',
                               80.0: 'STATE OF OKLAHOMA CREDIT ENH RESERVE FD GUARANTEE',
                               81.0: 'Vermont State Aid Intercept Program',
                               82.0: 'SOUTH DAKOTA ST AID INTERCEPT PROG',
                               83.0: 'NEW JERSEY SCH DIST ENHANCEMENT PROG CHAPTER 72',
                               84.0: 'NEW JERSEY QUALIFIED SCHOOL BOND PROGRAM',
                               85.0: 'NEW JERSEY SCH DIST ENHANCEMENT PROG - CHAPTER 74',
                               86.0: 'OKLAHOMA SCH DIST BOND GUARANTEE PROGRAM',
                               87.0: 'SOUTH DAKOTA SCH DIST CAPITAL OUTLAY LEASE PROGRAM',
                               88.0: 'CALIFORNIA MOTOR VEHICLE LICENSE FEE PROG',
                               89.0: 'CALIFORNIA ST TEACHERS RETIREMENT SYS',
                               90.0: 'OHIO MARKET ACCESS PROGRAM',
                               91.0: 'ARIZONA PUBLIC SCHOOL CREDIT ENHANCEMENT PROGRAM',
                               92.0: 'MICHIGAN CNTYS DISTRIBUTABLE ST AID INTERCEPT PROG',
                               93.0: 'CITY OF DETROIT DISTRIBUTABLE ST AID INTERCEPT PG',
                               94.0: 'OTHER ENH TYPE',
                               95.0: 'UTAH CHARTER SCHOOL CREDIT ENHANCEMENT PROGRAM'}
