'''
 # @ Author: Ahmad Shayaan
 # @ Create Time: 2021-12-17 12:07:51
 # @ Modified by: Mitas Ray
 # @ Modified time: 2022-01-14 23:07:00
 # @ Description:
 '''

NUM_OF_DAYS_IN_YEAR = 360

COUPON_FREQUENCY_DICT = {0:"Unknown",
                        1:"Semiannually",
                        2:"Monthly",
                        3:"Annually",
                        4:"Weekly",
                        5:"Quarterly",
                        6:"Every 2 years",
                        7:"Every 3 years",
                        8:"Every 4 years",
                        9:"Every 5 years",
                        10:"Every 7 years",
                        11:"Every 8 years",
                        12:"Biweekly",
                        13:"Changeable",
                        14:"Daily",
                        15:"Term mode",
                        16:"Interest at maturity",
                        17:"Bimonthly",
                        18:"Every 13 weeks",
                        19:"Irregular",
                        20:"Every 28 days",
                        21:"Every 35 days",
                        22:"Every 26 weeks",
                        23:"Not Applicable",
                        24:"Tied to prime",
                        25:"One time",
                        26:"Every 10 years",
                        27:"Frequency to be determined",
                        28:"Mandatory put",
                        29:"Every 52 weeks",
                        30:"When interest adjusts-commercial paper",
                        31:"Zero coupon",
                        32:"Certain years only",
                        33:"Under certain circumstances",
                        34:"Every 15 years",
                        35:"Custom",
                        36:"Single Interest Payment"}

LARGE_NUMBER = 1e6
VERY_LARGE_NUMBER = 1e9

COUPON_FREQUENCY_TYPE = {"Unknown":LARGE_NUMBER,
                         "Semiannually":2,
                         "Monthly":12,
                         "Annually":1,
                         "Weekly":52,
                         "Quarterly":4,
                         "Every 2 years":0.5,
                         "Every 3 years":1/3,
                         "Every 4 years":0.25,
                         "Every 5 years":0.2,
                         "Every 7 years":1/7,
                         "Every 8 years":1/8,
                         "Every 10 years":1/10,
                         "Biweekly": 26,
                         "Changeable":44,
                         "Daily":360,
                         "Interest at maturity":0,
                         "Not Applicable":LARGE_NUMBER}

IDENTIFIERS = ['rtrs_control_number', 'cusip']


BINARY = ['callable',
          'sinking',
          'zerocoupon',
          'is_non_transaction_based_compensation',
          'is_general_obligation',
          'callable_at_cav',           
          'extraordinary_make_whole_call', 
          'make_whole_call',
          'has_unexpired_lines_of_credit',
          'escrow_exists',
          ]

CATEGORICAL_FEATURES = ['rating',
                        'incorporated_state_code',
                        'trade_type',
                        'transaction_type',
                        'maturity_description_code',
                        'purpose_class']

NON_CAT_FEATURES = ['quantity',
                    'days_to_maturity',
                    'days_to_call',
                    'coupon',
                    'issue_amount',
                    'last_seconds_ago',
                    'last_yield_spread',
                    'days_to_settle',
                    'days_to_par',
                    'maturity_amount',
                    'issue_price', 
                    'orig_principal_amount',
                    'max_amount_outstanding',
                    'accrued_days',
                    'days_in_interest_payment']

TRADE_HISTORY = ['trade_history']
TARGET = ['yield_spread']

PREDICTORS = BINARY + CATEGORICAL_FEATURES + NON_CAT_FEATURES + TARGET + TRADE_HISTORY

PURPOSE_CLASS_DICT = {1.0: 'Authority', 
                      2.0: 'Bond Anticipation Note', 
                      3.0: 'Building', 
                      4.0: 'Capital Loan Notes', 
                      5.0: 'Certificates Of Participation', 
                      6.0: 'Corporate Purpose', 
                      7.0: 'Drainage District', 
                      8.0: 'Economic Development Revenue', 
                      9.0: 'Education', 
                      10.0: 'Environment', 
                      11.0: 'Equipment', 
                      12.0: 'Federal Aid Note', 
                      13.0: 'Fire District', 
                      14.0: 'Flood Water Sewer Disposal', 
                      15.0: 'General Purpose', 
                      16.0: 'Grant Anticipation Note', 
                      17.0: 'Health', 
                      18.0: 'Housing', 
                      19.0: 'Improvement', 
                      20.0: 'Industrial Development Revenue', 
                      21.0: 'Library District', 
                      22.0: 'Metropolitan District', 
                      23.0: 'Miscellaneous', 
                      24.0: 'Municipal Bond Bank', 
                      25.0: 'Municipal Utilities District', 
                      26.0: 'Park District', 
                      27.0: 'Parking Authority', 
                      28.0: 'Pollution Control Revenue', 
                      29.0: 'Pool Financing Authority', 
                      30.0: 'Promissory Note', 
                      31.0: 'Public Housing Authority', 
                      32.0: 'Public Utility District', 
                      33.0: 'Racetrack/Casino', 
                      34.0: 'Recreation Authority', 
                      35.0: 'Revenue Anticipation Note', 
                      36.0: 'Sanitation District', 
                      37.0: 'School District', 
                      38.0: 'Special Assessment', 
                      39.0: 'Special Obligation', 
                      40.0: 'State and Federal Anticipation Note', 
                      41.0: 'State and Grant Anticipation Note', 
                      42.0: 'State Anticipation Notes', 
                      43.0: 'State Store', 
                      44.0: 'Tax and Revenue Anticipation', 
                      45.0: 'Tax Anticipation Note', 
                      46.0: 'Tax Revenue', 
                      47.0: 'Temporary Notes', 
                      48.0: 'Transportation', 
                      49.0: 'Tribal Bonds', 
                      50.0: 'Utility', 
                      51.0: 'Various Purpose', 
                      52.0: 'Veterans', 
                      53.0: 'Warrants'}